# Generated by Django 3.0.6 on 2020-05-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='REST_API',
            new_name='REST_API_Models',
        ),
    ]
